sudo: required

os:
  - linux
#  - osx

env:
#  - GS_VERSION=3.2.14 TEST=Error
#  - GS_VERSION=3.1.0.6 TEST=Upgrade
  - GS_VERSION=3.3.0 TEST=Upgrade_71
#  - GS_VERSION=3.2.14 TEST=Install
#  - GS_VERSION=2.4.8 TEST=Basic
#  - GS_VERSION=3.1.0.6 TEST=Basic
#  - GS_VERSION=3.2.14 TEST=Basic
#  - GS_VERSION=3.3.0 TEST=Basic
#  - GS_VERSION=3.3.0 TEST=Clients
#  - GS_VERSION=3.3.0 TEST=SmalltalkCI

matrix:
   exclude:
     - os: osx
       env: GS_VERSION=2.4.8 TEST=Basic
     - os: osx
       env: GS_VERSION=3.1.0.6 TEST=Upgrade
#   allow_failures:
#     - os: osx

addons:
  hosts:
    - travis.dev

before_script:
  - sudo hostname travis.dev
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true

script:
  - hostname
  - cat /etc/hosts
  - tests/testTravisCI.sh
