language: erlang

sudo: required

env:

  - GS_VERSION=3.1.0.6 TEST=Basic
  - GS_VERSION=3.2.9   TEST=Basic
#  - GS_VERSION=3.1.0.6 TEST=BasicTodeClient
#  - GS_VERSION=3.2.9   TEST=BasicTodeClient
#  - GS_VERSION=3.1.0.6 TEST=Projects1
#  - GS_VERSION=3.2.9   TEST=Projects1
#  - GS_VERSION=3.1.0.6 TEST=Projects2
#  - GS_VERSION=3.2.9   TEST=Projects2
#  - GS_VERSION=3.1.0.6 TEST=Magritte
#  - GS_VERSION=3.2.9   TEST=Magritte
#  - GS_VERSION=3.1.0.6 TEST=Pier300
##  - GS_VERSION=3.2.9   TEST=Pier300  # older versions of Seaside3.0 aren't loadable in 3.2 ... invalid UTF8 characters in WAXMLEncoder table
#  - GS_VERSION=3.1.0.6 TEST=Seaside3
#  - GS_VERSION=3.2.9   TEST=Seaside3
#  - GS_VERSION=3.1.0.6 TEST=Zinc
#  - GS_VERSION=3.2.9   TEST=Zinc

before_script:
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true

script:
  - tests/testTravisCI.sh
