sudo: required

os:
  - linux
  - osx

env:
  - GS_VERSION=3.2.12 TEST=Error
  - GS_VERSION=3.1.0.6  TEST=Upgrade
  - GS_VERSION=3.2.12  TEST=Install
  - GS_VERSION=2.4.7 TEST=Basic
  - GS_VERSION=3.1.0.6 TEST=Basic
  - GS_VERSION=3.2.12  TEST=Basic

matrix:
   allow_failures:
   - os: osx
   exclude:
     - GS_VERSION: 2.4.7
       os: osx
       TEST: Basic
     - GS_VERSION: 3.1.0.6
       os: osx
       TEST: Upgrade

addons:
  hosts:
    - travis.dev

before_script:
  - sudo hostname travis.dev
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true

script:
  - hostname
  - cat /etc/hosts
  - tests/testTravisCI.sh
