language: erlang

sudo: required

env:

#
  - GS_VERSION=3.2.10  TEST=Simple
  - GS_VERSION=3.1.0.6 TEST=Basic
  - GS_VERSION=3.2.10  TEST=Basic

#  - GS_VERSION=3.1.0.6 TEST=BasicTodeClient
#  - GS_VERSION=3.2.9   TEST=BasicTodeClient
#  - GS_VERSION=3.1.0.6 TEST=Projects1
#  - GS_VERSION=3.2.9   TEST=Projects1
#  - GS_VERSION=3.1.0.6 TEST=Projects2
#  - GS_VERSION=3.2.9   TEST=Projects2

addons:
  hosts:
    - travis.dev

before_script:
  - sudo hostname travis.dev
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true

script:
  - tests/testTravisCI.sh
