sudo: required

os:
  - linux
  - osx

env:
  - GS_VERSION=3.2.11  TEST=Error
  - GS_VERSION=3.2.11  TEST=Install
  - GS_VERSION=3.1.0.6 TEST=Basic
  - GS_VERSION=3.2.11  TEST=Basic
#  - GS_VERSION=3.2.11 TEST=BasicTodeClient

before_script:
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true

script:
  - tests/testTravisCI.sh
